# Generated by Django 3.0.2 on 2020-01-19 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_business'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('customer', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=4)),
                ('status', models.BooleanField()),
            ],
        ),
    ]
