# Generated by Django 3.0.2 on 2020-01-19 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_transactions'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Transactions',
            new_name='Transaction',
        ),
    ]
