# Generated by Django 3.0.2 on 2020-01-19 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_auto_20200119_0341'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=200)),
                ('month', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=4)),
                ('status', models.BooleanField()),
            ],
        ),
    ]
